apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup-task
spec:
  steps:
    - name: cleanup
      image: alpine
      script: |
        #!/bin/sh
        echo "Cleaning up resources..."
        oc delete all --all -n $(context.pipelineRun.namespace)
        echo "Cleanup completed."
